### PR TITLE
Restructured the WG-risk according to the guidelines

### PR DESCRIPTION
**Pull request by ritik-malik**
Hi,
I've added new directories for various metrics in the `focus-areas` directory,
for now I don't prefer to touch the old `metrics` directory` as it might be used by people for referring.

Also, I've downloaded the images which were hosted on `imgur` and referred in metrics, I added them to `images` dir.
I've not addressed the issue of naming conventions for metrics and their respective images. I plan to fix that in a different PR.

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @ritik-malik 

When we merge the changes for file location or name into chaoss:master, it creates more work for us.

I like your approach to have incrementally make and discuss the changes. So after we have consensus on the current changes, please update this PR with new commits for the next iteration of changes.

**Comment by GeorgLink** [comment]
I clicked through the files and it starts to look good. 

I appreciate that you downloaded the images and included them in the repository.

Please continue:
- update the naming of files and folders
- remove the /metrics folder, so that only the new structure exists

I think once that's all done, we can discuss the PR with the Working Group, get consensus, and merge it. Any changes after that can be done in different PRs because they will not change the name or location of files.

**Comment by ritik-malik** [comment]
Thanks for the feedback @GeorgLink !
I'll update here once I done with those 2 things

**Comment by ritik-malik** [comment]
Before removing the `metrics` folder, I saw that there are 2 metrics that are not listed in any focus-area :
1. [OSI Approved Licenses](https://github.com/chaoss/wg-risk/blob/master/metrics/OSI_Approved_Licenses.md)
2. [SPDX_Document](https://github.com/chaoss/wg-risk/blob/master/metrics/SPDX_Document.md)

How should I treat these 2 metrics?

**Comment by GeorgLink** [comment]
Please open an issue to ask about these metrics.
The WG members need to discuss and decide.

**Comment by ritik-malik** [comment]
Hi @GeorgLink ,
I've added those 2 metrics to `license` focus-area,
Also added them to the license README and deleted the `metrics` directory

**Review by GeorgLink — CHANGES_REQUESTED** [review]
This PR is almost ready.

The focus area link on the main README need to be fixed:
Screen Shot 2021-04-02 at 8 21 29 AM

I suggest replacing the list that's in the README now, with the table that we have in the Focus area folder:
Screen Shot 2021-04-02 at 8 25 13 AM

**Comment by ritik-malik** [comment]
Fixed the main `README.md`

**Review by GeorgLink — APPROVED** [review]
Thanks @ritik-malik 

This looks great!

**Comment by GeorgLink** [comment]
@sgoggins can you please take a look and merge when ready?

I saw you already created the backup release: https://github.com/chaoss/wg-risk/releases/tag/0.5.0
I think there was nothing else blocking this, right?

**Comment by klumb** [comment]
LGTM

**Review by sgoggins — APPROVED** [review]

**Pull request merged**
