### PR TITLE
License metrics

### PR DESCRIPTION
**Pull request by sgoggins**
These are the three license metrics defined by the working group in initial GitHub draft form.

### CODE REVIEW

**Comment by klumb** [comment]
@sgoggins is Augur the only known implementation? Also, should that be a link to the Augur site?

**Comment by germonprez** [comment]
I suspect that Augur is the only known implementation for this. Particularly from a CHAOSS tools perspective. The only other that might be worth checking out (but this could be done during the open period) would be FOSSology. 

Yes, a link to AUGUR would be good... just the repo.

**Comment by GeorgLink** [comment]
> @sgoggins is Augur the only known implementation? Also, should that be a link to the Augur site?

I'm pinging @alpgarcia and @valeriocos to see whether GrimoireLab has something. I think the [CoLic backend to Graal](https://github.com/chaoss/grimoirelab-graal#backends) has license information.

**Comment by valeriocos** [comment]
The CoLic backend provides license info (raw data), however the implementation of specific metrics (and visualizations) is an ongoing work in the context GSoC (cc @inishchith).

**Comment by inishchith** [comment]
@valeriocos Sorry for the delayed response.
Yes, We're about to start some work on it by later this week (As currently, we're getting ready with the first iteration of some visualizations with the help of CoCom backend data).
Please let me know if we're looking at something specific, we can have a discussion on it :)

Thanks!

**Comment by GeorgLink** [comment]
I'll create a new issue to continue discussing GrimoireLab visualization for license information. This pull request may be merged and closed.

**Comment by klumb** [comment]
@georg, does it need its own issue or do you want to wait and add it the release comment issues?

**Comment by GeorgLink** [comment]
@klumb I opened a new issue #13 to not delay this pull request. I would handle it separately from the general release comment issues because it is very specific enhancement and not a feedback.

**Comment by sgoggins** [comment]
@GeorgLink : I merged with approval and encourage modification during the evaluation period.

**Pull request merged**
