### PR TITLE
Renamed Bus Factor metric to Contributor Absence Factor 

### PR DESCRIPTION
**Pull request by geekygirldawn**
The reason for this change can be found in https://github.com/chaoss/community/issues/632. 

To minimize disruption, this first PR simply changes the text of the metric without changing any filenames to minimize disruption while we transition to the new name.

This PR should be merged by @klumb or @ElizabethN in coordination with putting a 301 "Moved Permanently" redirect in place from https://chaoss.community/kb/metric-bus-factor/ to https://chaoss.community/?p=3944

### CODE REVIEW

**Comment by klumb** [comment]
@geekygirldawn & @ElizabethN 

I changed the URL name on the website, added a 301 redirect, changed the edit link at the bottom of the page, and added bus factor as a searchable key word for this metric. 

@geekygirldawn did you change the Github url for this metric in the PR? I didn't see that but maybe am missing it.

**Comment by geekygirldawn** [comment]
I did not change the GH URL. Since those don't redirect, and realistically no one sees the GH URL, I left it as is.

**Comment by klumb** [comment]
Okay, I assumed that was gong to change as well so I made that change on the website as well.

**Comment by klumb** [comment]
Should I change it back on the website or merge this and make another pull to change the URL name here? 

I believe GitHub handles the redirect automatically.

**Comment by geekygirldawn** [comment]
OK, I think I've fixed things with those 2 new commits.

**Comment by klumb** [comment]
@geekygirldawn, everything appears to be working

**Pull request merged**
